version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "3000:3000"
